-- Menu content for the mock restaurant "Sage & Ember".
-- Seed data is real application data here (the menu ships with the product),
-- so it lives in a versioned migration and also runs in prod.

INSERT INTO menu_categories (name, display_order)
VALUES ('Starters', 1),
       ('Mains', 2),
       ('Wood-Fired Pizza', 3),
       ('Desserts', 4),
       ('Drinks', 5);

INSERT INTO menu_items (category_id, name, description, price_cents, image_url)
VALUES
    ((SELECT id FROM menu_categories WHERE name = 'Starters'),
     'Charred Shishito Peppers', 'Blistered shishitos, smoked sea salt, yuzu aioli', 900,
     'https://picsum.photos/seed/shishito/600/400'),
    ((SELECT id FROM menu_categories WHERE name = 'Starters'),
     'Crispy Calamari', 'Buttermilk-battered calamari, pickled fresno chiles, lemon caper remoulade', 1400,
     'https://picsum.photos/seed/calamari/600/400'),
    ((SELECT id FROM menu_categories WHERE name = 'Starters'),
     'Burrata & Heirloom Tomato', 'Creamy burrata, heirloom tomatoes, basil oil, grilled sourdough', 1300,
     'https://picsum.photos/seed/burrata/600/400'),
    ((SELECT id FROM menu_categories WHERE name = 'Starters'),
     'Smoked Chicken Flatbread', 'Applewood-smoked chicken, charred corn, chipotle crema', 1200,
     'https://picsum.photos/seed/flatbread/600/400'),

    ((SELECT id FROM menu_categories WHERE name = 'Mains'),
     'Pan-Seared Salmon', 'Crispy-skin salmon, spring pea risotto, meyer lemon beurre blanc', 2800,
     'https://picsum.photos/seed/salmon/600/400'),
    ((SELECT id FROM menu_categories WHERE name = 'Mains'),
     'Braised Short Rib', '12-hour braised short rib, smoked cheddar grits, charred broccolini', 3200,
     'https://picsum.photos/seed/shortrib/600/400'),
    ((SELECT id FROM menu_categories WHERE name = 'Mains'),
     'Herb-Roasted Half Chicken', 'Free-range half chicken, fingerling potatoes, salsa verde', 2400,
     'https://picsum.photos/seed/chicken/600/400'),
    ((SELECT id FROM menu_categories WHERE name = 'Mains'),
     'Wild Mushroom Risotto', 'Carnaroli rice, roasted wild mushrooms, parmesan, truffle oil', 2100,
     'https://picsum.photos/seed/risotto/600/400'),
    ((SELECT id FROM menu_categories WHERE name = 'Mains'),
     'Grilled Ribeye', '14oz prime ribeye, bone marrow butter, hand-cut fries', 3900,
     'https://picsum.photos/seed/ribeye/600/400'),

    ((SELECT id FROM menu_categories WHERE name = 'Wood-Fired Pizza'),
     'Margherita', 'San Marzano tomato, fior di latte, fresh basil, olive oil', 1600,
     'https://picsum.photos/seed/margherita/600/400'),
    ((SELECT id FROM menu_categories WHERE name = 'Wood-Fired Pizza'),
     'Spicy Soppressata', 'Soppressata, calabrian chili honey, smoked mozzarella', 1900,
     'https://picsum.photos/seed/soppressata/600/400'),
    ((SELECT id FROM menu_categories WHERE name = 'Wood-Fired Pizza'),
     'Forest Mushroom & Taleggio', 'Roasted mushrooms, taleggio, thyme, garlic cream', 1800,
     'https://picsum.photos/seed/mushroompizza/600/400'),

    ((SELECT id FROM menu_categories WHERE name = 'Desserts'),
     'Basque Cheesecake', 'Burnt basque cheesecake, macerated berries', 1100,
     'https://picsum.photos/seed/cheesecake/600/400'),
    ((SELECT id FROM menu_categories WHERE name = 'Desserts'),
     'Dark Chocolate Torte', 'Flourless chocolate torte, espresso cream, cocoa nib brittle', 1200,
     'https://picsum.photos/seed/torte/600/400'),
    ((SELECT id FROM menu_categories WHERE name = 'Desserts'),
     'Seasonal Fruit Crisp', 'Baked seasonal fruit, oat streusel, vanilla bean ice cream', 1000,
     'https://picsum.photos/seed/crisp/600/400'),

    ((SELECT id FROM menu_categories WHERE name = 'Drinks'),
     'House Lemonade', 'Fresh-pressed lemonade with rosemary syrup', 500,
     'https://picsum.photos/seed/lemonade/600/400'),
    ((SELECT id FROM menu_categories WHERE name = 'Drinks'),
     'Cold Brew', 'Single-origin cold brew over ice', 600,
     'https://picsum.photos/seed/coldbrew/600/400'),
    ((SELECT id FROM menu_categories WHERE name = 'Drinks'),
     'Local IPA', 'Rotating draft from local breweries, 16oz', 800,
     'https://picsum.photos/seed/ipa/600/400'),
    ((SELECT id FROM menu_categories WHERE name = 'Drinks'),
     'Old Fashioned', 'Rye whiskey, demerara, angostura, orange peel', 1400,
     'https://picsum.photos/seed/oldfashioned/600/400'),
    ((SELECT id FROM menu_categories WHERE name = 'Drinks'),
     'Pinot Noir', 'Willamette Valley pinot noir, 6oz pour', 1300,
     'https://picsum.photos/seed/pinot/600/400');
